Repository samply/blaze, pull requests merged in 2021-06, with the labels that each got.

#401 Migrate to AdoptOpenJDK
  .github/containerscan/allowedlist.yaml
  Dockerfile
Labels: operation, security

#402 Migrate to a Java 15 Runtime
  Dockerfile
Labels: operation

#400 Fix Query Param _format Override
  modules/rest-api/src/blaze/rest_api.clj
  modules/rest-api/src/blaze/rest_api/middleware/output.clj
  modules/rest-api/test/blaze/rest_api/middleware/log_test.clj
  modules/rest-api/test/blaze/rest_api/middleware/output_test.clj
  modules/rest-api/test/blaze/rest_api/middleware/resource_test.clj
  modules/rest-api/test/blaze/rest_api_test.clj
Labels: bug, module:rest-api

#403 Update Dependencies
  .github/workflows/build.yml
  deps.edn
  modules/byte-string/deps.edn
  modules/cql/src/blaze/elm/spec.clj
  modules/fhir-structure/deps.edn
  modules/module-base/deps.edn
Labels: dependencies

#380 Allow SSL Kafka Connections
  .github/distributed-test/blaze.keystore.jks
  .github/distributed-test/cassandra-init.cql
  .github/distributed-test/docker-compose.yml
  .github/distributed-test/kafka-init.conf
  .github/distributed-test/kafka-init.sh
  .github/distributed-test/kafka-topic-creator.keystore.jks
  .github/distributed-test/kafka.keystore.jks
  .github/distributed-test/kafka.truststore.jks
  .github/openid-auth-test/docker-compose.yml
  .github/scripts/install-blazectl.sh
  .github/scripts/revinclude.sh
  .github/workflows/build.yml
  README.md
  cassandra/docker-compose.yml
  docs/deployment/distributed.md
  docs/deployment/distributed/blaze-1.keystore.jks
  docs/deployment/distributed/blaze-2.keystore.jks
  docs/deployment/distributed/cassandra-init.cql
  docs/deployment/distributed/docker-compose.yml
  docs/deployment/distributed/haproxy.cfg
  docs/deployment/distributed/kafka-init.conf
  docs/deployment/distributed/kafka-init.sh
  docs/deployment/distributed/kafka-topic-creator.keystore.jks
  docs/deployment/distributed/kafka.keystore.jks
  docs/deployment/distributed/kafka.truststore.jks
  docs/deployment/docker-deployment.md
  docs/deployment/environment-variables.md
  docs/deployment/manual-deployment.md
  kafka/docker-compose.yml
  modules/db-resource-store-cassandra/src/blaze/db/resource_store/cassandra.clj
  modules/db-resource-store-cassandra/src/blaze/db/resource_store/cassandra/log.clj
  modules/db-resource-store-cassandra/test/blaze/db/resource_store/cassandra/log_test.clj
  modules/db-tx-log-kafka/src/blaze/db/tx_log/kafka.clj
  modules/db-tx-log-kafka/src/blaze/db/tx_log/kafka/config.clj
  modules/db-tx-log-kafka/src/blaze/db/tx_log/kafka/log.clj
  modules/db-tx-log-kafka/src/blaze/db/tx_log/kafka/spec.clj
  modules/db-tx-log-kafka/test/blaze/db/tx_log/kafka/config_test.clj
  modules/db-tx-log-kafka/test/blaze/db/tx_log/kafka/log_test.clj
  modules/db-tx-log-kafka/test/blaze/db/tx_log/kafka_test.clj
  modules/interaction/src/blaze/interaction/transaction.clj
  resources/blaze.edn
  src/blaze/core.clj
Labels: enhancement, module:db-tx-log-kafka, operation

#404 Document the CQL API
  .github/distributed-test/docker-compose.yml
  .github/workflows/build.yml
  docs/cql-queries.md
  docs/cql-queries/api.md
  docs/cql-queries/command-line.md
  evaluate-measure.sh
Labels: documentation

#405 Implement Type Age for Quantity Search Param
  modules/db/src/blaze/db/impl/search_param/quantity.clj
  modules/db/test/blaze/db/api_test.clj
Labels: enhancement, module:db

#406 Remove Search Params from Module Structure Definition
  modules/structure-definition/resources/blaze/fhir/r4/search-parameters.json
  modules/structure-definition/src/blaze/structure_definition.clj
Labels: refactoring

#407 Implement Search Parameters of Type Number
  docs/implementation/database.md
  modules/anomaly/src/blaze/anomaly.clj
  modules/db/src/blaze/db/impl/codec.clj
  modules/db/src/blaze/db/impl/search_param.clj
  modules/db/src/blaze/db/impl/search_param/composite.clj
  modules/db/src/blaze/db/impl/search_param/number.clj
  modules/db/src/blaze/db/impl/search_param/quantity.clj
  modules/db/src/blaze/db/node.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/impl/search_param/composite_test.clj
  modules/db/test/blaze/db/impl/search_param/number_test.clj
  modules/db/test/blaze/db/impl/search_param/quantity_test.clj
Labels: enhancement, module:db

#409 Override the base URL when Forwarded Headers are Present
  .github/distributed-test/docker-compose.yml
  .github/scripts/forwarded-header.sh
  .github/scripts/x-forwarded-headers.sh
  .github/workflows/build.yml
  README.md
  docs/api.md
  docs/deployment/environment-variables.md
  modules/interaction/src/blaze/interaction/create.clj
  modules/interaction/src/blaze/interaction/history/instance.clj
  modules/interaction/src/blaze/interaction/history/system.clj
  modules/interaction/src/blaze/interaction/history/type.clj
  modules/interaction/src/blaze/interaction/history/util.clj
  modules/interaction/src/blaze/interaction/search/nav.clj
  modules/interaction/src/blaze/interaction/search/util.clj
  modules/interaction/src/blaze/interaction/search_compartment.clj
  modules/interaction/src/blaze/interaction/search_system.clj
  modules/interaction/src/blaze/interaction/search_type.clj
  modules/interaction/src/blaze/interaction/spec.clj
  modules/interaction/src/blaze/interaction/transaction.clj
  modules/interaction/src/blaze/interaction/update.clj
  modules/interaction/test/blaze/interaction/create_test.clj
  modules/interaction/test/blaze/interaction/history/instance_test.clj
  modules/interaction/test/blaze/interaction/history/system_test.clj
  modules/interaction/test/blaze/interaction/history/type_test.clj
  modules/interaction/test/blaze/interaction/history/util_spec.clj
  modules/interaction/test/blaze/interaction/history/util_test.clj
  modules/interaction/test/blaze/interaction/search/nav_spec.clj
  modules/interaction/test/blaze/interaction/search/nav_test.clj
  modules/interaction/test/blaze/interaction/search_compartment_test.clj
  modules/interaction/test/blaze/interaction/search_system_test.clj
  modules/interaction/test/blaze/interaction/search_type_test.clj
  modules/interaction/test/blaze/interaction/transaction_test.clj
  modules/interaction/test/blaze/interaction/update_test.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/handler/impl.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/handler/impl_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_spec.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
  modules/rest-api/src/blaze/rest_api.clj
  modules/rest-api/src/blaze/rest_api/middleware/forwarded.clj
  modules/rest-api/test/blaze/rest_api/middleware/forwarded_test.clj
  modules/rest-api/test/blaze/rest_api_test.clj
  modules/rest-util/src/blaze/fhir/response/create.clj
  modules/rest-util/src/blaze/fhir/response/create_spec.clj
  modules/rest-util/src/blaze/handler/fhir/util.clj
  modules/rest-util/src/blaze/handler/fhir/util_spec.clj
  modules/rest-util/src/blaze/handler/util.clj
  modules/rest-util/src/blaze/http/util.clj
  modules/rest-util/src/blaze/http/util/spec.clj
  modules/rest-util/src/blaze/http/util_spec.clj
  modules/rest-util/test/blaze/fhir/response/create_test.clj
  modules/rest-util/test/blaze/handler/fhir/util_test.clj
  modules/rest-util/test/blaze/http/util_test.clj
Labels: enhancement, module:rest-api, module:rest-util

#411 Update Dependencies
  deps.edn
  modules/db-resource-store-cassandra/deps.edn
Labels: dependencies

#413 Use Implementation of ge/le for gt/lt in Date Search Params
  modules/db/src/blaze/db/impl/search_param/date.clj
  modules/db/test/blaze/db/api_test.clj
Labels: enhancement, module:db

#415 Add Platform arm64 to Docker Build
  .github/workflows/build.yml
Labels: operation

#418 Cleanup
  .github/scripts/authenticated-request.sh
  .github/scripts/check-capability-statement.sh
  .github/scripts/download-resources.sh
  .github/scripts/forwarded-header.sh
  .github/scripts/install-blazectl.sh
  .github/scripts/revinclude.sh
  .github/scripts/x-forwarded-headers.sh
  .github/workflows/build.yml
  modules/spec/README.md
  modules/structure-definition/src/blaze/structure_definition.clj
Labels: refactoring

#425 Add Specs to Arithmetic Operators
  modules/cql/src/blaze/elm/compiler/arithmetic_operators.clj
  modules/cql/src/blaze/elm/protocols.clj
  modules/cql/test/blaze/elm/compiler/arithmetic_operators_spec.clj
  modules/cql/test/blaze/elm/compiler/arithmetic_operators_test.clj
Labels: module:cql
