Repository samply/blaze, pull requests merged in 2022-12, with the labels that each got.

#850 ConceptRef
  modules/cql/src/blaze/elm/compiler/clinical_values.clj
  modules/cql/src/blaze/elm/compiler/external_data.clj
  modules/cql/src/blaze/elm/spec.clj
  modules/cql/test/blaze/elm/compiler/clinical_values_test.clj
  modules/cql/test/blaze/elm/compiler/external_data_test.clj
  modules/cql/test/blaze/elm/literal.clj
  modules/cql/test/blaze/elm/literal_spec.clj
  modules/cql/test/blaze/elm/ratio_spec.clj
  modules/cql/test/data_readers.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q48-concept.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q48-concept.json
Labels: enhancement, module:cql

#852 Update Dependencies
  modules/byte-buffer/deps.edn
  modules/byte-string/deps.edn
  modules/fhir-structure/deps.edn
  modules/rest-util/deps.edn
Labels: dependencies

#851 Return CodeableConcepts as is for Strata
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/stratifier.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_test.clj
Labels: enhancement, module:evaluate-measure

#853 Add a Backport of R5 Quantity Stratum Values
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/stratifier.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_test.clj
Labels: enhancement, module:evaluate-measure

#855 Update Jepsen
  modules/jepsen/deps.edn
Labels: dependencies

#856 Update CQL-to-ELM Translator
  deps.edn
  modules/cql/deps.edn
  modules/cql/resources/blaze/fhir-modelinfo-4.0.0.xml
  modules/cql/resources/org/hl7/elm_modelinfo/r1/jaxb.properties
  modules/cql/src/blaze/cql_translator.clj
  modules/cql/src/blaze/elm/compiler/library.clj
  modules/cql/src/blaze/elm/compiler/reusing_logic.clj
  modules/cql/test/blaze/elm/compiler/external_data_test.clj
  modules/cql/test/blaze/elm/compiler/reusing_logic_test.clj
  modules/cql/test/blaze/elm/compiler/structured_values_test.clj
  modules/fhir-path/deps.edn
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
Labels: module:cql, dependencies

#858 Decrease size of docker image
  Dockerfile
Labels: operation

#861 Use Tools Build
  Dockerfile
  Makefile
  build.clj
  deps.edn
  docs/deployment/manual-deployment.md
  modules/byte-string/deps.edn
  modules/cql/Makefile
  modules/db-resource-store-cassandra/Makefile
  modules/db-resource-store/Makefile
  modules/db-tx-log-kafka/Makefile
  modules/db-tx-log/Makefile
  modules/db/Makefile
  modules/db/test/data_readers.clj
  modules/interaction/Makefile
  modules/metrics/Makefile
  modules/metrics/build.clj
  modules/metrics/deps.edn
  modules/metrics/src/blaze/metrics/Collector.clj
  modules/metrics/src/blaze/metrics/core.clj
  modules/operation-measure-evaluate-measure/Makefile
  modules/page-store-cassandra/Makefile
  modules/page-store/Makefile
  modules/rest-api/Makefile
  modules/rest-util/Makefile
  modules/rocksdb/Makefile
  modules/thread-pool-executor-collector/Makefile
  pom.xml
  src/blaze/core.clj
Labels: refactoring, dependencies

#863 Update Dependencies
  .github/workflows/build.yml
  modules/byte-buffer/deps.edn
  modules/byte-string/deps.edn
Labels: dependencies

#865 Implement CQL toConcept
  docs/conformance/cql.md
  modules/cql/src/blaze/elm/code.clj
  modules/cql/src/blaze/elm/compiler/type_operators.clj
  modules/cql/src/blaze/elm/deps_infer.clj
  modules/cql/src/blaze/elm/list.clj
  modules/cql/src/blaze/elm/nil.clj
  modules/cql/src/blaze/elm/protocols.clj
  modules/cql/test/blaze/elm/compiler/type_operators_test.clj
  modules/cql/test/blaze/elm/literal.clj
  modules/cql/test/blaze/elm/literal_spec.clj
  modules/cql/test/data_readers.clj
Labels: enhancement, module:cql

#866 Improve Hashing Performance
  modules/fhir-structure/src/blaze/fhir/spec/type.clj
  modules/fhir-structure/src/blaze/fhir/spec/type/macros.clj
  modules/fhir-structure/test-perf/blaze/fhir/hash_test_perf.clj
Labels: performance, module:fhir-structure

#864 Fix Date Search
  dev/blaze/dev/decompiler.clj
  modules/byte-buffer/src/blaze/byte_buffer.clj
  modules/db/src/blaze/db/impl/codec.clj
  modules/db/src/blaze/db/impl/codec/date.clj
  modules/db/src/blaze/db/impl/search_param/date.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/impl/codec/date_spec.clj
  modules/db/test/blaze/db/impl/codec/date_test.clj
  modules/db/test/blaze/db/impl/codec_spec.clj
  modules/db/test/blaze/db/impl/codec_test.clj
  modules/db/test/blaze/db/impl/search_param/date_test.clj
  modules/db/test/blaze/db/impl/search_param_test.clj
  modules/db/test/blaze/db/node/resource_indexer_test.clj
  modules/fhir-structure/src/blaze/fhir/spec/type/system/spec.clj
Labels: bug, module:db

#867 Update Dependencies
  deps.edn
  modules/byte-buffer/deps.edn
  modules/byte-string/deps.edn
  modules/cassandra/deps.edn
  modules/test-util/deps.edn
Labels: dependencies

#868 Push Docker Image after Integration Tests
  .github/scripts/revinclude.sh
  .github/workflows/build.yml
Labels: refactoring
