Repository samply/blaze, pull requests merged in 2022-04, with the labels that each got.

#667 Update RocksDB to v7.0.4
  modules/rocksdb/deps.edn
Labels: module:db-rocksdb, dependencies

#668 Update Jackson Databind to v2.13.2.2
  modules/byte-string/deps.edn
Labels: security, dependencies

#669 Update GitHub Actions Cache to v3
  .github/workflows/build.yml
Labels: dependencies

#663 Improve DB Module Performance
  dev/blaze/dev/decompiler.clj
  docs/implementation/database.md
  modules/byte-buffer/src/blaze/byte_buffer.clj
  modules/byte-string/src/blaze/byte_string.clj
  modules/coll/src/blaze/coll/core.clj
  modules/coll/src/blaze/coll/core_spec.clj
  modules/db/.clj-kondo/config.edn
  modules/db/src/blaze/db/impl/batch_db.clj
  modules/db/src/blaze/db/impl/codec.clj
  modules/db/src/blaze/db/impl/db.clj
  modules/db/src/blaze/db/impl/index.clj
  modules/db/src/blaze/db/impl/index/compartment/resource.clj
  modules/db/src/blaze/db/impl/index/compartment/search_param_value_resource.clj
  modules/db/src/blaze/db/impl/index/resource_as_of.clj
  modules/db/src/blaze/db/impl/index/resource_handle.clj
  modules/db/src/blaze/db/impl/index/resource_search_param_value.clj
  modules/db/src/blaze/db/impl/index/search_param_value_resource.clj
  modules/db/src/blaze/db/impl/index/search_param_value_resource/impl.clj
  modules/db/src/blaze/db/impl/index/system_as_of.clj
  modules/db/src/blaze/db/impl/index/type_as_of.clj
  modules/db/src/blaze/db/impl/iterators.clj
  modules/db/src/blaze/db/impl/search_param/string.clj
  modules/db/src/blaze/db/impl/search_param/token.clj
  modules/db/src/blaze/db/impl/search_param/util.clj
  modules/db/src/blaze/db/node.clj
  modules/db/test-perf/blaze/db/api_test_perf.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/impl/codec/spec.clj
  modules/db/test/blaze/db/impl/codec_spec.clj
  modules/db/test/blaze/db/impl/codec_test.clj
  modules/db/test/blaze/db/impl/index/compartment/search_param_value_resource_spec.clj
  modules/db/test/blaze/db/impl/index/resource_handle_spec.clj
  modules/db/test/blaze/db/impl/index/search_param_value_resource/impl_test.clj
  modules/db/test/blaze/db/impl/index/search_param_value_resource_test.clj
  modules/kv/src/blaze/db/kv/mem.clj
  modules/kv/test/blaze/db/kv/mem_test.clj
  modules/rocksdb/src/blaze/db/kv/rocksdb/metrics.clj
  modules/rocksdb/test/blaze/db/kv/rocksdb/metrics_test.clj
Labels: performance

#670 Update Clojure to v1.11.0
  .github/workflows/build.yml
  deps.edn
  modules/async/src/blaze/async/comp.clj
  modules/byte-string/src/blaze/byte_string.clj
  modules/cassandra/deps.edn
  modules/cql/src/blaze/elm/compiler/simple_values.clj
  modules/cql/src/blaze/elm/decimal.clj
  modules/cql/src/blaze/elm/integer.clj
  modules/cql/src/blaze/elm/protocols.clj
  modules/cql/src/blaze/elm/spec.clj
  modules/cql/test/blaze/elm/compiler/simple_values_test.clj
  modules/db-resource-store-cassandra/test/blaze/db/resource_store/cassandra_test.clj
  modules/db/src/blaze/db/impl/codec.clj
  modules/db/test/blaze/db/api_test.clj
  modules/fhir-path/src/blaze/fhir_path.clj
  modules/fhir-structure/deps.edn
  modules/fhir-structure/src/blaze/fhir/spec/type.clj
  modules/fhir-structure/src/blaze/fhir/spec/type/system.clj
  modules/interaction/src/blaze/interaction/history/util.clj
  modules/interaction/src/blaze/interaction/util.clj
  modules/jepsen/src/blaze/jepsen/register.clj
  modules/luid/test/blaze/luid_test.clj
  modules/module-base/deps.edn
  modules/rest-util/src/blaze/handler/fhir/util.clj
  modules/rest-util/src/blaze/middleware/fhir/db.clj
  modules/rest-util/test/blaze/handler/fhir/util_test.clj
  modules/rest-util/test/blaze/middleware/fhir/db_test.clj
  modules/server/src/blaze/server.clj
  modules/server/src/blaze/server/spec.clj
  modules/spec/deps.edn
  src/blaze/system.clj
Labels: dependencies

#672 Update Protobuf to v3.20.0
  modules/byte-buffer/deps.edn
  modules/byte-string/deps.edn
Labels: dependencies

#673 Update Codecov GitHub Action to v3
  .github/workflows/build.yml
Labels: dependencies

#674 Various Refactorings
  modules/byte-buffer/src/blaze/byte_buffer.clj
  modules/byte-buffer/test/blaze/byte_buffer_test.clj
  modules/byte-string/src/blaze/byte_string.clj
  modules/coll/deps.edn
  modules/coll/src/blaze/coll/core.clj
  modules/coll/src/blaze/coll/core_spec.clj
  modules/coll/test/blaze/coll/core_test.clj
  modules/cql/src/blaze/elm/compiler/aggregate_operators.clj
  modules/cql/src/blaze/elm/list.clj
  modules/cql/test/blaze/elm/literal.clj
  modules/db-protocols/src/blaze/db/impl/protocols.clj
  modules/db/src/blaze/db/impl/db.clj
  modules/db/src/blaze/db/impl/index/compartment/resource.clj
  modules/db/src/blaze/db/impl/index/compartment/search_param_value_resource.clj
  modules/db/src/blaze/db/impl/index/resource_as_of.clj
  modules/db/src/blaze/db/impl/index/resource_handle.clj
  modules/db/src/blaze/db/impl/index/system_as_of.clj
  modules/db/src/blaze/db/impl/index/type_as_of.clj
  modules/db/src/blaze/db/impl/search_param.clj
  modules/db/src/blaze/db/impl/search_param/composite/common.clj
  modules/db/src/blaze/db/impl/search_param/has.clj
  modules/db/src/blaze/db/impl/search_param/token.clj
  modules/db/src/blaze/db/impl/search_param/util.clj
  modules/db/src/blaze/db/node/tx_indexer/verify.clj
  modules/db/test-perf/blaze/db/impl/index/resource_handle_test_perf.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/impl/codec_test.clj
  modules/db/test/blaze/db/impl/index/resource_handle_spec.clj
  modules/db/test/blaze/db/impl/index/resource_handle_test.clj
  modules/db/test/blaze/db/impl/index/search_param_value_resource/impl_test.clj
  modules/db/test/blaze/db/impl/index/search_param_value_resource_test.clj
  modules/db/test/blaze/db/impl/search_param/composite_test.clj
  modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
  modules/fhir-path/src/blaze/fhir_path.clj
  modules/fhir-structure/deps.edn
  modules/fhir-structure/src/blaze/fhir/spec/type.clj
  modules/fhir-structure/src/blaze/fhir/spec/type/macros.clj
  modules/page-store/src/blaze/page_store/weigh.clj
  modules/rocksdb/src/blaze/db/kv/rocksdb/impl.clj
Labels: refactoring

#675 Update Dependencies
  .github/workflows/build.yml
  deps.edn
  modules/rest-util/deps.edn
  modules/server/deps.edn
Labels: dependencies

#677 Update clj-kondo
  .github/workflows/build.yml
Labels: dependencies

#679 Update Dependencies
  .github/workflows/build.yml
  deps.edn
  modules/anomaly/deps.edn
  modules/async/deps.edn
  modules/byte-buffer/deps.edn
  modules/cassandra/deps.edn
  modules/coll/deps.edn
  modules/cql/deps.edn
  modules/db-resource-store-cassandra/deps.edn
  modules/db-resource-store/deps.edn
  modules/db-tx-log-kafka/deps.edn
  modules/db-tx-log/deps.edn
  modules/db/deps.edn
  modules/executor/deps.edn
  modules/extern-terminology-service/deps.edn
  modules/fhir-client/deps.edn
  modules/fhir-path/deps.edn
  modules/fhir-structure/deps.edn
  modules/http-client/deps.edn
  modules/interaction/deps.edn
  modules/jepsen/deps.edn
  modules/kv/deps.edn
  modules/luid/deps.edn
  modules/metrics/deps.edn
  modules/openid-auth/deps.edn
  modules/operation-measure-evaluate-measure/deps.edn
  modules/page-store-cassandra/deps.edn
  modules/page-store/deps.edn
  modules/rest-api/deps.edn
  modules/rest-util/deps.edn
  modules/rocksdb/deps.edn
  modules/scheduler/deps.edn
  modules/server/deps.edn
  modules/thread-pool-executor-collector/deps.edn
Labels: dependencies

#681 Update Dependencies
  modules/cassandra/deps.edn
  modules/rocksdb/deps.edn
Labels: dependencies

#684 Update Dependencies
  .github/workflows/build.yml
  modules/byte-buffer/deps.edn
  modules/byte-string/deps.edn
  modules/cql/deps.edn
  modules/fhir-path/deps.edn
  modules/rocksdb/deps.edn
Labels: dependencies

#688 Add Reverse Include Values into CapabilityStatement
  modules/db/src/blaze/db/search_param_registry.clj
  modules/db/src/blaze/db/search_param_registry_spec.clj
  modules/db/test/blaze/db/search_param_registry_test.clj
  modules/rest-api/src/blaze/rest_api/capabilities.clj
  modules/rest-api/test/blaze/rest_api/capabilities_test.clj
Labels: enhancement

#682 Implement CQL ToBoolean
  modules/cql/src/blaze/elm/boolean.clj
  modules/cql/src/blaze/elm/compiler/type_operators.clj
  modules/cql/src/blaze/elm/decimal.clj
  modules/cql/src/blaze/elm/integer.clj
  modules/cql/src/blaze/elm/nil.clj
  modules/cql/src/blaze/elm/protocols.clj
  modules/cql/src/blaze/elm/string.clj
  modules/cql/test/blaze/elm/compiler/type_operators_test.clj
  modules/cql/test/blaze/elm/literal.clj
  modules/cql/test/data_readers.clj
  modules/fhir-structure/src/blaze/fhir/spec/type/system.clj
Labels: enhancement, module:cql

#691 Chained Search Params
  .github/scripts/download-resources-query.sh
  .github/workflows/build.yml
  deps.edn
  docs/performance/fhir-search.md
  modules/db/.clj-kondo/config.edn
  modules/db/resources/blaze/db/search-parameters.json
  modules/db/src/blaze/db/impl/batch_db.clj
  modules/db/src/blaze/db/impl/codec.clj
  modules/db/src/blaze/db/impl/db.clj
  modules/db/src/blaze/db/impl/index.clj
  modules/db/src/blaze/db/impl/index/resource_as_of.clj
  modules/db/src/blaze/db/impl/index/resource_handle.clj
  modules/db/src/blaze/db/impl/index/resource_search_param_value.clj
  modules/db/src/blaze/db/impl/macros.clj
  modules/db/src/blaze/db/impl/search_param.clj
  modules/db/src/blaze/db/impl/search_param/chained.clj
  modules/db/src/blaze/db/impl/search_param/has.clj
  modules/db/src/blaze/db/impl/search_param/list.clj
  modules/db/src/blaze/db/impl/search_param/token.clj
  modules/db/src/blaze/db/impl/search_param/util.clj
  modules/db/src/blaze/db/node.clj
  modules/db/test-perf/blaze/db/impl/index/resource_handle_test_perf.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/impl/index/resource_handle_spec.clj
  modules/db/test/blaze/db/impl/index/resource_handle_test.clj
  modules/db/test/blaze/db/impl/index/resource_search_param_value_spec.clj
  modules/db/test/blaze/db/impl/index_spec.clj
  modules/interaction/src/blaze/interaction/util.clj
  modules/interaction/test/blaze/interaction/search_type_test.clj
  modules/interaction/test/blaze/interaction/util_test.clj
Labels: enhancement

#695 Implement CQL ToChars
  modules/cql/src/blaze/elm/compiler/type_operators.clj
  modules/cql/test/blaze/elm/compiler/type_operators_test.clj
  modules/cql/test/blaze/elm/literal.clj
  modules/cql/test/data_readers.clj
Labels: enhancement, module:cql
