Repository samply/blaze, pull requests merged in 2022-10, with the labels that each got.

#806 Update Dependencies
  deps.edn
  dev/blaze/dev.clj
  dev/blaze/dev/tx_log.clj
  modules/byte-buffer/deps.edn
  modules/byte-string/deps.edn
  modules/cassandra/src/blaze/cassandra/config.clj
  modules/cassandra/test/blaze/cassandra/config_test.clj
  modules/cql/src/blaze/elm/date_time.clj
  modules/cql/src/blaze/elm/expression_spec.clj
  modules/cql/test/blaze/elm/compiler/date_time_operators_test.clj
  modules/db-stub/src/blaze/db/api_stub.clj
  modules/db-tx-log-kafka/deps.edn
  modules/db-tx-log-kafka/test/blaze/db/tx_log/kafka_test.clj
  modules/db-tx-log/src/blaze/db/tx_log_spec.clj
  modules/db-tx-log/test/blaze/db/tx_log_test.clj
  modules/db/src/blaze/db/node.clj
  modules/db/src/blaze/db/tx_log/local.clj
  modules/db/test-perf/blaze/db/api_test_perf.clj
  modules/db/test/blaze/db/test_util.clj
  modules/db/test/blaze/db/tx_log/local_test.clj
  modules/fhir-structure/test/blaze/fhir/spec/type/system_test.clj
  modules/http-client/test/blaze/http_client_test.clj
  modules/interaction/test/blaze/interaction/history/instance_test.clj
  modules/interaction/test/blaze/interaction/history/system_test.clj
  modules/interaction/test/blaze/interaction/history/type_test.clj
  modules/interaction/test/blaze/interaction/search_compartment_test.clj
  modules/interaction/test/blaze/interaction/search_system_test.clj
  modules/interaction/test/blaze/interaction/search_type_test.clj
  modules/luid/test/blaze/luid_test.clj
  modules/openid-auth/src/blaze/openid_auth.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_spec.clj
  modules/page-store/src/blaze/page_store/local.clj
  modules/rocksdb/deps.edn
  modules/scheduler/src/blaze/scheduler.clj
  modules/scheduler/src/blaze/scheduler_spec.clj
  modules/scheduler/test/blaze/scheduler_test.clj
  modules/server/deps.edn
  modules/spec/deps.edn
  modules/spec/src/blaze/spec.clj
  modules/test-util/deps.edn
Labels: dependencies

#812 Add Date Component CQL Test
  modules/cql/test/blaze/elm/compiler/comparison_operators_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q46-between-date-data.json
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q46-between-date-query.cql
Labels: module:cql, module:evaluate-measure

#814 Add Release Badge
  README.md
Labels: documentation

#795 Implement CQL Is
  docs/conformance/cql.md
  modules/cql/src/blaze/elm/compiler/type_operators.clj
  modules/cql/test/blaze/cql_test.clj
  modules/cql/test/blaze/elm/compiler/type_operators_test.clj
  modules/cql/test/blaze/elm/literal.clj
  modules/cql/test/data_readers.clj
Labels: enhancement, module:cql

#817 Update Dependencies
  modules/byte-string/deps.edn
  modules/cassandra/deps.edn
Labels: dependencies

#822 Fix Storage of Bundles with References
  .github/test-data/bundle-with-references/bundle.json
  .github/workflows/build.yml
  modules/fhir-structure/src/blaze/fhir/spec/type.clj
  modules/fhir-structure/test/blaze/fhir/spec/generators.clj
  modules/fhir-structure/test/blaze/fhir/spec/type_test.clj
  modules/fhir-structure/test/blaze/fhir/spec_test.clj
  modules/interaction/test/blaze/interaction/create_test.clj
Labels: bug, module:fhir-structure

#824 Update Dependencies
  .github/workflows/build.yml
  deps.edn
  modules/anomaly/deps.edn
  modules/async/deps.edn
  modules/byte-buffer/deps.edn
  modules/byte-string/deps.edn
  modules/cassandra/deps.edn
  modules/coll/deps.edn
  modules/cql/deps.edn
  modules/db-resource-store-cassandra/deps.edn
  modules/db-resource-store/deps.edn
  modules/db-tx-log-kafka/deps.edn
  modules/db-tx-log/deps.edn
  modules/db/deps.edn
  modules/executor/deps.edn
  modules/extern-terminology-service/deps.edn
  modules/fhir-client/deps.edn
  modules/fhir-path/deps.edn
  modules/fhir-structure/deps.edn
  modules/http-client/deps.edn
  modules/interaction/deps.edn
  modules/jepsen/deps.edn
  modules/kv/deps.edn
  modules/luid/deps.edn
  modules/metrics/deps.edn
  modules/openid-auth/deps.edn
  modules/operation-measure-evaluate-measure/deps.edn
  modules/page-store-cassandra/deps.edn
  modules/page-store/deps.edn
  modules/rest-api/deps.edn
  modules/rest-util/deps.edn
  modules/rocksdb/deps.edn
  modules/scheduler/deps.edn
  modules/server/deps.edn
  modules/thread-pool-executor-collector/deps.edn
Labels: dependencies
