Repository samply/blaze, pull requests merged in 2023-02, with the labels that each got.

#895 Add CQL Documentation
  docs/conformance/cql.md
  modules/cql/src/blaze/elm/compiler/queries.clj
  modules/cql/test/blaze/elm/compiler/library_test.clj
  modules/cql/test/blaze/elm/compiler/queries_test.clj
  modules/cql/test/blaze/elm/compiler/simple_values_test.clj
Labels: module:cql, documentation

#897 Cleanup DBOptions Handling
  modules/rocksdb/src/blaze/db/kv/rocksdb.clj
Labels: module:rocksdb, cleanup

#898 Update Dependencies
  .github/workflows/build.yml
  deps.edn
  modules/byte-string/deps.edn
  modules/cassandra/deps.edn
  modules/cql/deps.edn
  modules/fhir-path/deps.edn
  modules/fhir-structure/deps.edn
  modules/http-client/deps.edn
  modules/metrics/deps.edn
Labels: dependencies

#899 Update Dependencies
  modules/db-tx-log-kafka/deps.edn
Labels: dependencies

#902 Refactor Database Node Init Tests
  modules/db-resource-store/src/blaze/db/resource_store/spec.clj
  modules/db-tx-log/src/blaze/db/tx_log/spec.clj
  modules/db/src/blaze/db/search_param_registry/spec.clj
  modules/db/src/blaze/db/spec.clj
  modules/db/test/blaze/db/node/resource_indexer_test.clj
  modules/db/test/blaze/db/node_test.clj
  modules/db/test/blaze/db/resource_cache_test.clj
  modules/db/test/blaze/db/search_param_registry_test.clj
  modules/fhir-structure/src/blaze/fhir/structure_definition_repo/spec.clj
Labels: refactoring

#905 Fix _lastUpdated Search Returning a Resource more than Once
  modules/db-stub/src/blaze/db/api_stub.clj
  modules/db/src/blaze/db/impl/batch_db.clj
  modules/db/src/blaze/db/impl/search_param/all.clj
  modules/db/src/blaze/db/impl/search_param/date.clj
  modules/db/src/blaze/db/impl/search_param/quantity.clj
  modules/db/src/blaze/db/impl/search_param/util.clj
  modules/db/src/blaze/db/node.clj
  modules/db/test-perf/blaze/db/api_test_perf.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/test_util.clj
  modules/db/test/blaze/db/tx_log/local_test.clj
  modules/fhir-structure/src/blaze/fhir/hash.clj
  modules/interaction/test/blaze/interaction/create_test.clj
  modules/interaction/test/blaze/interaction/history/instance_test.clj
  modules/interaction/test/blaze/interaction/history/system_test.clj
  modules/interaction/test/blaze/interaction/history/type_test.clj
  modules/interaction/test/blaze/interaction/search_compartment_test.clj
  modules/interaction/test/blaze/interaction/search_system_test.clj
  modules/interaction/test/blaze/interaction/search_type_test.clj
  modules/interaction/test/blaze/interaction/transaction_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj
  modules/test-util/src/blaze/test_util.clj
  test/blaze/system_test.clj
Labels: bug

#906 Update Dependencies
  .github/workflows/build.yml
  deps.edn
  modules/cassandra/deps.edn
  modules/fhir-structure/deps.edn
  modules/page-store/deps.edn
Labels: dependencies

#910 Fix System Search Paging
  .github/scripts/download-all-resources.sh
  .github/workflows/build.yml
  modules/db/test/blaze/db/search_param_registry_test.clj
  modules/interaction/src/blaze/interaction/search_system.clj
  modules/rest-api/src/blaze/rest_api/routes.clj
Labels: bug, module:rest-api

#912 Update Dependencies
  deps.edn
  modules/cassandra/deps.edn
  modules/cql/deps.edn
  modules/fhir-path/deps.edn
Labels: dependencies

#913 Update Blazectl
  .github/scripts/download-all-resources.sh
  .github/scripts/download-resources.sh
  .github/scripts/install-blazectl.sh
Labels: dependencies

#911 Improve Documentation of Data Sync
  .github/distributed-test/docker-compose.yml
  .github/doc-copy-data-test/docker-compose.override.yml
  .github/openid-auth-test/docker-compose.yml
  .github/workflows/build.yml
  docker-compose.yml
  docs/authentication/docker-compose.yml
  docs/consistency/docker-compose.yml
  docs/data-sync.md
  docs/data-sync/copy/docker-compose.yml
  docs/data-sync/docker-compose.yml
  docs/data-sync/subscription/docker-compose.yml
  docs/data-sync/subscription/subscription-bundle.json
  docs/deployment/distributed/docker-compose.yml
  scripts/copy-data.sh
  scripts/save-data.sh
  test-scripts/patient.json
  test-scripts/system-history-paging.json
  test-scripts/type-history-paging.json
Labels: documentation

#919 Allow Writing Large Binary Resources in XML Format
  .github/scripts/generate-large-binary-resource.sh
  .github/workflows/build.yml
  docker-compose.yml
  modules/fhir-structure/deps.edn
  modules/rest-api/src/blaze/rest_api/middleware/resource.clj
  modules/rest-api/test/blaze/rest_api/middleware/resource_test.clj
Labels: bug, module:rest-api

#922 Prevent Outputting the Large Binary Resource in CI
  .github/workflows/build.yml
Labels: test-fix

#923 Implement Special Search Parameter _elements
  .github/scripts/download-all-resources.sh
  .github/scripts/download-observations-elements.sh
  .github/scripts/download-resources.sh
  .github/scripts/evaluate-measure-subject-list.sh
  .github/workflows/build.yml
  docs/performance/fhir-search.md
  docs/performance/fhir-search/simple-code-search.sh
  modules/db-protocols/src/blaze/db/impl/protocols.clj
  modules/db/src/blaze/db/api.clj
  modules/db/src/blaze/db/api_spec.clj
  modules/db/src/blaze/db/cache_collector.clj
  modules/db/src/blaze/db/impl/batch_db.clj
  modules/db/src/blaze/db/impl/db.clj
  modules/db/src/blaze/db/node.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/cache_collector_test.clj
  modules/interaction/src/blaze/interaction/search/nav.clj
  modules/interaction/src/blaze/interaction/search/params.clj
  modules/interaction/src/blaze/interaction/search_compartment.clj
  modules/interaction/src/blaze/interaction/search_system.clj
  modules/interaction/src/blaze/interaction/search_type.clj
  modules/interaction/src/blaze/interaction/transaction.clj
  modules/interaction/src/blaze/interaction/update.clj
  modules/interaction/src/blaze/interaction/util.clj
  modules/interaction/test/blaze/interaction/search/nav_spec.clj
  modules/interaction/test/blaze/interaction/search/nav_test.clj
  modules/interaction/test/blaze/interaction/search/params_test.clj
  modules/interaction/test/blaze/interaction/search_type_test.clj
  modules/interaction/test/blaze/interaction/transaction_test.clj
  modules/interaction/test/blaze/interaction/update_test.clj
  modules/rest-util/src/blaze/handler/fhir/util/spec.clj
  modules/rest-util/src/blaze/handler/fhir/util_spec.clj
Labels: enhancement, module:db, module:interaction

#925 Improve Performance
  docs/performance/fhir-search.md
  modules/db/src/blaze/db/impl/index/resource_handle.clj
  modules/db/src/blaze/db/node.clj
  modules/db/src/blaze/db/search_param_registry.clj
  modules/fhir-structure/src/blaze/fhir/spec/type.clj
  modules/interaction/src/blaze/interaction/history/instance.clj
  modules/interaction/src/blaze/interaction/history/system.clj
  modules/interaction/src/blaze/interaction/history/type.clj
  modules/interaction/src/blaze/interaction/history/util.clj
  modules/interaction/src/blaze/interaction/search/nav.clj
  modules/interaction/src/blaze/interaction/search/params/include.clj
  modules/interaction/src/blaze/interaction/search/util.clj
  modules/interaction/src/blaze/interaction/search_compartment.clj
  modules/interaction/src/blaze/interaction/search_system.clj
  modules/interaction/src/blaze/interaction/search_type.clj
  modules/interaction/src/blaze/interaction/transaction.clj
  modules/interaction/test/blaze/interaction/history/instance_test.clj
  modules/interaction/test/blaze/interaction/history/system_test.clj
  modules/interaction/test/blaze/interaction/history/type_test.clj
  modules/interaction/test/blaze/interaction/history/util_test.clj
  modules/interaction/test/blaze/interaction/search_compartment_test.clj
  modules/interaction/test/blaze/interaction/search_system_test.clj
  modules/interaction/test/blaze/interaction/search_type_test.clj
  modules/interaction/test/blaze/interaction/transaction_test.clj
  modules/module-base/src/blaze/util.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
  modules/rest-util/src/blaze/handler/fhir/util.clj
  modules/rest-util/test/blaze/handler/fhir/util_test.clj
Labels: module:db, performance, module:interaction, module:rest-util

#926 Fix FHIR Search Performance Documentation
  docs/performance/fhir-search.md
Labels: documentation
