Repository samply/blaze, pull requests merged in 2024-11, with the labels that each got.

#2179 Improve Internal DB Specs
  modules/db-tx-log/src/blaze/db/tx_log/spec.clj
  modules/db/.clj-kondo/config.edn
  modules/db/src/blaze/db/node.clj
  modules/db/src/blaze/db/node/tx_indexer/verify.clj
  modules/db/test/blaze/db/impl/index/rts_as_of_spec.clj
  modules/db/test/blaze/db/node/tx_indexer/expand_spec.clj
  modules/db/test/blaze/db/node/tx_indexer/expand_test.clj
  modules/db/test/blaze/db/node/tx_indexer/verify/spec.clj
  modules/db/test/blaze/db/node/tx_indexer/verify_spec.clj
  modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
Labels: module:db

#2199 job-ig: stop using external Terminology server
  job-ig/Makefile
Labels: ci

#2205 fix: make sure all namespace-specific def's are private
  modules/rest-util/test/blaze/middleware/fhir/output_test.clj
Labels: cleanup

#2206 fix: replace `are` with `doseq` in `given`
  modules/rest-util/test/blaze/middleware/fhir/output_test.clj
Labels: cleanup

#2217 Fix Response Status Code for Failing XML Emits
  modules/rest-util/src/blaze/middleware/fhir/output.clj
  modules/rest-util/test/blaze/middleware/fhir/output_test.clj
Labels: bug, module:rest-util

#2220 Add More CQL Tests
  modules/cql/test/blaze/cql/translator_test.clj
  modules/cql/test/blaze/elm/compiler/reusing_logic_test.clj
Labels: module:cql
