Repository samply/blaze, pull requests merged in 2024-12, with the labels that each got.

#2229 Use Equivalent Instead of Contains for Code Comparison
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q10.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q16.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q28-relationship-procedure-condition.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q3.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q45-histology.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q6.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q9.cql
Labels: cleanup

#2240 Update Frontend Dependencies
  modules/frontend/package-lock.json
Labels: dependencies, module:frontend

#2241 Implement Parameter _total in FHIR Search
  .github/scripts/download-resources-query.sh
  docs/api.md
  modules/interaction/src/blaze/interaction/search/nav.clj
  modules/interaction/src/blaze/interaction/search/params.clj
  modules/interaction/src/blaze/interaction/search_type.clj
  modules/interaction/test/blaze/interaction/search_type_test.clj
Labels: enhancement, module:interaction

#2119 Implement Download of Binary Resources
  .github/scripts/install-xq.sh
  .github/scripts/read-binary-content-not-found.sh
  .github/scripts/read-binary-content-via-json-found.sh
  .github/scripts/read-binary-content-via-xml-found.sh
  .github/workflows/build.yml
  modules/rest-api/src/blaze/rest_api/routes.clj
  modules/rest-api/src/blaze/rest_api/spec.clj
  modules/rest-util/src/blaze/middleware/fhir/output.clj
  modules/rest-util/test/blaze/middleware/fhir/output_test.clj
Labels: enhancement, module:rest-api, module:rest-util

#2254 Override Cookie Dependency to v1.0.0
  modules/frontend/package-lock.json
  modules/frontend/package.json
Labels: security, dependencies, module:frontend

#2258 Update Doc Dependencies
  docs/package-lock.json
Labels: documentation, dependencies

#2260 Move Node Version to .nvmrc
  .github/workflows/build.yml
  .nvmrc
Labels: dependencies

#2271 Update Node to v23.4.0
  .nvmrc
Labels: dependencies, ci

#2272 Update Clojure Tools Build to v0.10.6
  deps.edn
  modules/db/deps.edn
  modules/fhir-structure/deps.edn
  modules/job-async-interaction/deps.edn
  modules/job-compact/deps.edn
  modules/job-re-index/deps.edn
  modules/job-scheduler/deps.edn
  modules/kv/deps.edn
  modules/metrics/deps.edn
  modules/server/deps.edn
Labels: dependencies

#2285 Simplify Terminology Service Error Messages
  .github/value-set-expand/expand-all.sh
  modules/operation-code-system-validate-code/test/blaze/fhir/operation/code_system/validate_code_test.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/default.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/sct.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/ucum.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/util.clj
  modules/terminology-service/src/blaze/terminology_service/local/value_set.clj
  modules/terminology-service/src/blaze/terminology_service/local/value_set/expand.clj
  modules/terminology-service/test/blaze/terminology_service/local_test.clj
Labels: cleanup

#2286 Pass Simple Expand Terminology Tests
  .github/scripts/install-validator.sh
  .github/terminology-tests/.gitignore
  .github/terminology-tests/all.sh
  .github/terminology-tests/parameters-expand.sh
  .github/terminology-tests/simple-expand.sh
  .github/terminology-tests/validation-simple.sh
  .github/validation/.gitignore
  .github/validation/Makefile
  .github/validation/validate-medication.sh
  .github/value-set-expand/Abrechnungsart.csv
  .github/value-set-expand/mii-vs-consent-policy.csv
  .github/workflows/build.yml
  .gitignore
  modules/fhir-structure/src/blaze/fhir/spec/spec.clj
  modules/operation-value-set-expand/src/blaze/fhir/operation/value_set/expand.clj
  modules/operation-value-set-expand/test/blaze/fhir/operation/value_set/expand_test.clj
  modules/terminology-service/src/blaze/terminology_service/local.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/core.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/default.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/filter/equals.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/filter/exists.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/filter/regex.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/sct.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/ucum.clj
  modules/terminology-service/src/blaze/terminology_service/local/graph.clj
  modules/terminology-service/src/blaze/terminology_service/local/value_set.clj
  modules/terminology-service/src/blaze/terminology_service/local/value_set/expand.clj
  modules/terminology-service/src/blaze/terminology_service/spec.clj
  modules/terminology-service/test/blaze/terminology_service/local/code_system/spec.clj
  modules/terminology-service/test/blaze/terminology_service/local/code_system_spec.clj
  modules/terminology-service/test/blaze/terminology_service/local/graph/spec.clj
  modules/terminology-service/test/blaze/terminology_service/local/graph_spec.clj
  modules/terminology-service/test/blaze/terminology_service/local/graph_test.clj
  modules/terminology-service/test/blaze/terminology_service/local/value_set/spec.clj
  modules/terminology-service/test/blaze/terminology_service/local/value_set_spec.clj
  modules/terminology-service/test/blaze/terminology_service/local_test.clj
Labels: enhancement
