Repository samply/blaze, pull requests merged in 2024-05, with the labels that each got.

#1689 Make global repl explicit + docs improvements
  DEVELOPMENT.md
  Makefile
Labels: documentation

#1705 Cleanup fhir-structure Dependencies
  modules/fhir-structure/deps.edn
Labels: cleanup

#1710 Remove Need for FHIR Validator Local Package Cache
  .github/scripts/admin-api/create-invalid-jobs.sh
  .github/scripts/jobs/re-index/create-invalid-job.sh
  .github/workflows/build.yml
  Dockerfile
  job-ig/Makefile
  modules/admin-api/deps.edn
  modules/admin-api/resources/blaze/admin_api/StructureDefinition-CompactJob.json
  modules/admin-api/src/blaze/admin_api.clj
  modules/admin-api/src/blaze/admin_api/validation.clj
  modules/admin-api/test/blaze/admin_api_test.clj
  modules/page-store/src/blaze/page_store/local.clj
  modules/rest-util/deps.edn
Labels: operation

#1720 Update commons-compress to v0.16.1
  modules/admin-api/deps.edn
Labels: security, dependencies, module:admin-api

#1731 Lower Memory Consumption while Evaluating Stratifiers
  .github/scripts/cql/stratifier-condition-code.cql
  .github/scripts/cql/stratifier-condition-code.csv
  .github/scripts/cql/stratifier-condition-code.yml
  .github/scripts/evaluate-measure-blazectl-stratifier.sh
  .github/workflows/build.yml
  docs/performance/cql.md
  docs/performance/cql/observation-code-search.sh
  docs/performance/cql/stratifier-condition-code.cql
  docs/performance/cql/stratifier-condition-code.yml
  docs/performance/cql/stratifier-observation-laboratory-code.cql
  docs/performance/cql/stratifier-observation-laboratory-code.yml
  modules/cql/src/blaze/elm/compiler/library/spec.clj
  modules/cql/src/blaze/elm/compiler/library_spec.clj
  modules/db-resource-store/src/blaze/db/resource_store/kv.clj
  modules/db/src/blaze/db/tx_log/local.clj
  modules/fhir-structure/src/blaze/fhir/spec/spec.clj
  modules/interaction/src/blaze/interaction/transaction.clj
  modules/interaction/src/blaze/interaction/util.clj
  modules/luid/src/blaze/luid.clj
  modules/luid/src/blaze/luid/spec.clj
  modules/luid/src/blaze/luid_spec.clj
  modules/luid/test/blaze/luid_test.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/cql.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/group.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/population.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/stratifier.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/measure/util.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql/spec.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_spec.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/cql_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/group_spec.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/population/spec.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/population_spec.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier/spec.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_spec.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/stratifier_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/util_spec.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure/util_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/measure_test.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q54-stratifier-condition-code.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q54-stratifier-condition-code.json
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q55-stratifier-bmi-observation.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q55-stratifier-bmi-observation.json
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q56-stratifier-observation-code-value.cql
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure/q56-stratifier-observation-code-value.json
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj
Labels: module:evaluate-measure, performance, module:luid

#1721 Fix Delivering too Many Search Results in Some Cases
  modules/db/src/blaze/db/impl/search_param/token.clj
  modules/db/test/blaze/db/api_test.clj
Labels: bug, module:db
