Repository samply/blaze, pull requests merged in 2024-09, with the labels that each got.

#2008 Make sure we return 422 on non-existing measure POST requests (Fixes #512)
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure.clj
  modules/operation-measure-evaluate-measure/src/blaze/fhir/operation/evaluate_measure/middleware/params.clj
  modules/operation-measure-evaluate-measure/test/blaze/fhir/operation/evaluate_measure_test.clj
Labels: bug, module:evaluate-measure

#2016 Fix CI
  .github/workflows/build.yml
  modules/operation-patient-everything/Makefile
  modules/page-id-cipher/Makefile
Labels: ci

#2017 Fix Parsing of Dates starting with a Zero in the Year Component
  .github/scripts/create-patient-with-ancient-birth-year.sh
  .github/workflows/build.yml
  modules/fhir-structure/java/blaze/fhir/spec/type/system/DateTimeYear.java
  modules/fhir-structure/java/blaze/fhir/spec/type/system/DateYear.java
  modules/fhir-structure/test/blaze/fhir/spec/generators.clj
  modules/fhir-structure/test/blaze/fhir/spec/type_test.clj
Labels: bug, module:fhir-structure

#2019 Patient $everything Ignores Query Params when Paging
  .github/scripts/patient-everything-paged-date-range.sh
  .github/workflows/build.yml
  modules/operation-patient-everything/src/blaze/operation/patient/everything.clj
  modules/operation-patient-everything/test/blaze/operation/patient/everything_test.clj
Labels: bug, module:patient-everything

#2020 Update Pages Deps and Fix Deploy
  .github/workflows/build.yml
  docs/package-lock.json
Labels: documentation, dependencies

#2021 Update Tools Build
  deps.edn
  modules/db/deps.edn
  modules/fhir-structure/deps.edn
  modules/job-async-interaction/deps.edn
  modules/job-compact/deps.edn
  modules/job-re-index/deps.edn
  modules/job-scheduler/deps.edn
  modules/kv/deps.edn
  modules/metrics/deps.edn
Labels: dependencies

#2022 Update FHIR Utils because of CVE-2024-26308
  modules/admin-api/deps.edn
Labels: security, dependencies, module:admin-api

#2023 Update clj-kondo to v2024.08.29
  .github/workflows/build.yml
Labels: dependencies, ci

#2025 Update Frontend
  modules/frontend/package-lock.json
Labels: dependencies, module:frontend

#2029 Fix False Positives while Checking Referential Integrity
  modules/db/src/blaze/db/impl/batch_db.clj
  modules/db/src/blaze/db/impl/index/resource_handle.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/impl/index/resource_handle_spec.clj
Labels: bug, module:db

#2035 Add nREPL support
  DEVELOPMENT.md
  Makefile
  deps.edn
  dev/blaze/dev.clj
Labels: enhancement, documentation

#2038 Update Clojure in CI
  .github/workflows/build.yml
Labels: dependencies, ci

#2039 Add new Function to the Byte Buffer Module
  modules/byte-buffer/src/blaze/byte_buffer.clj
  modules/byte-buffer/src/blaze/byte_buffer_spec.clj
  modules/byte-buffer/test/blaze/byte_buffer_test.clj
  modules/db/src/blaze/db/impl/codec/date.clj
  modules/db/src/blaze/db/impl/index/compartment/resource.clj
  modules/db/src/blaze/db/impl/index/compartment/search_param_value_resource.clj
  modules/db/src/blaze/db/impl/index/resource_search_param_value.clj
  modules/db/src/blaze/db/impl/index/search_param_value_resource.clj
  modules/db/test/blaze/db/impl/index/compartment/resource_spec.clj
  modules/db/test/blaze/db/impl/index/compartment/search_param_value_resource_spec.clj
  modules/db/test/blaze/db/impl/index/search_param_value_resource_spec.clj
  modules/db/test/blaze/db/impl/index/system_as_of_spec.clj
  modules/db/test/blaze/db/impl/index/type_as_of_spec.clj
  modules/db/test/blaze/db/impl/iterators_spec.clj
  modules/db/test/blaze/db/impl/iterators_test.clj
Labels: refactoring, module:db, module:byte-buffer

#2036 Overhaul DEVELOPMENT
  DEVELOPMENT.md
Labels: documentation

#2045 Update Clojure to v1.12.0.1479
  .github/workflows/build.yml
  modules/byte-string/deps.edn
  modules/db/deps.edn
Labels: dependencies, ci

#2051 Add delete-history and history-instance Functions
  modules/fhir-client/Makefile
  modules/fhir-client/src/blaze/fhir_client.clj
  modules/fhir-client/src/blaze/fhir_client_spec.clj
  modules/fhir-client/test/blaze/fhir_client_test.clj
Labels: enhancement, module:fhir-client

#2052 Make more Reducible Collections Counted
  cljfmt.edn
  modules/coll/.clj-kondo/config.edn
  modules/coll/src/blaze/coll/core.clj
  modules/coll/test/blaze/coll/core_test.clj
  modules/cql/.clj-kondo/config.edn
  modules/db/src/blaze/db/impl/iterators.clj
  modules/db/test/blaze/db/api_test.clj
Labels: refactoring, module:db, module:coll

#2061 Add Load Testing Scripts and Doc
  docs/performance/load-testing.md
  modules/load-test/.gitignore
  modules/load-test/README.md
  modules/load-test/package-lock.json
  modules/load-test/package.json
  modules/load-test/patient-everything.js
  modules/load-test/read-single-patient.js
  modules/load-test/script.js
Labels: documentation, load-testing

#2062 Don't Create a Version for Double Deletes
  modules/db/src/blaze/db/node/tx_indexer/verify.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
  modules/load-test/Makefile
Labels: enhancement, module:db

#2072 Refactor How Purging Reflects in Resource Handles
  modules/db/src/blaze/db/impl/index/resource_as_of.clj
  modules/db/src/blaze/db/impl/index/resource_handle.clj
  modules/db/src/blaze/db/impl/index/system_as_of.clj
  modules/db/src/blaze/db/impl/index/type_as_of.clj
  modules/db/test-perf/blaze/db/impl/index/resource_handle_test_perf.clj
  modules/db/test/blaze/db/impl/index/resource_handle_spec.clj
  modules/db/test/blaze/db/impl/index/resource_handle_test.clj
Labels: refactoring, module:db

#2073 Tackle Trivy Rate Limit Issues
  .github/workflows/build.yml
Labels: ci

#2074 Update Frontend Dependencies
  modules/frontend/package-lock.json
Labels: dependencies, module:frontend

#2075 Update Docs Dependencies
  docs/package-lock.json
Labels: documentation, dependencies

#2079 Update Frontend e2e Playwright
  modules/frontend-e2e/package-lock.json
Labels: dependencies, module:frontend

#2084 Enable Keep-Alive Backend Connections on Ingress
  docs/performance/load-testing.md
  modules/ingress/default.conf.template
  modules/load-test/Makefile
  modules/load-test/http-req-duration.jq
  modules/load-test/patient-everything.js
  modules/load-test/read-single-patient.js
  modules/load-test/report.sh
Labels: performance, module:ingress

#2083 Implement Operation Patient $purge
  .github/scripts/conditional-delete-type/delete-all-resources-of-type.sh
  .github/scripts/patient-purge.sh
  .github/workflows/build.yml
  deps.edn
  docs/api.md
  docs/api/operation-patient-purge.md
  docs/implementation/database.md
  modules/db-tx-log/src/blaze/db/tx_log/spec.clj
  modules/db/src/blaze/db/node/transaction.clj
  modules/db/src/blaze/db/node/tx_indexer/expand.clj
  modules/db/src/blaze/db/node/tx_indexer/verify.clj
  modules/db/src/blaze/db/spec.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/node/tx_indexer/expand_test.clj
  modules/db/test/blaze/db/node/tx_indexer/verify_test.clj
  modules/operation-patient-purge/.clj-kondo/config.edn
  modules/operation-patient-purge/Makefile
  modules/operation-patient-purge/README.md
  modules/operation-patient-purge/deps.edn
  modules/operation-patient-purge/src/blaze/operation/patient/purge.clj
  modules/operation-patient-purge/test/blaze/operation/patient/purge_test.clj
  modules/operation-patient-purge/tests.edn
  modules/rest-api/src/blaze/rest_api/routes.clj
  modules/rest-api/src/blaze/rest_api/spec.clj
  modules/rest-api/test/blaze/rest_api/routes_test.clj
  modules/rest-util/src/blaze/middleware/fhir/resource.clj
  modules/rest-util/test/blaze/middleware/fhir/resource_test.clj
  resources/blaze.edn
Labels: enhancement, module:db, module:rest-util, dependencies, module:patient-purge

#2087 Try to Fix Trivy Rate Limit Problems Again
  .github/workflows/build.yml
Labels: ci
