Repository samply/blaze, pull requests merged in 2025-05, with the labels that each got.

#2629 Remove Trivy DB Config
  .github/workflows/build.yml
Labels: ci

#2631 Update Frontend Dependencies
  modules/frontend-e2e/package-lock.json
  modules/frontend/package-lock.json
Labels: dependencies

#2470 Update FHIR Validator to v6.5.21
  .github/scripts/install-validator.sh
  .github/validation/validate.sh
  docs/terminology-service/validation.md
Labels: dependencies

#2642 Add Some more CQL Tests
  modules/cql/test/blaze/elm/compiler/date_time_operators_test.clj
  modules/cql/test/blaze/elm/compiler/interval_operators_test.clj
  modules/cql/test/blaze/elm/compiler/queries_test.clj
Labels: module:cql

#2652 Update Frontend Dependencies
  modules/frontend/eslint.config.js
  modules/frontend/package-lock.json
  modules/frontend/package.json
Labels: dependencies

#2653 Update prom-metrics to v0.6-alpha.8
  modules/module-base/deps.edn
Labels: dependencies

#2655 Fix Caching of prom-metrics Git Repo
  deps.edn
  job-ig/Makefile
  modules/admin-api/deps.edn
  modules/cql/deps.edn
  modules/extern-terminology-service/deps.edn
  modules/fhir-structure/build.clj
  modules/frontend-e2e/Makefile
  modules/frontend-e2e/test-data/Makefile
  modules/job-compact/deps.edn
  modules/job-scheduler/deps.edn
  modules/job-util/deps.edn
  modules/kv/Makefile
  modules/kv/build.clj
  modules/luid/deps.edn
  modules/operation-code-system-validate-code/deps.edn
  modules/operation-measure-evaluate-measure/deps.edn
  modules/operation-value-set-expand/deps.edn
  modules/operation-value-set-validate-code/deps.edn
  modules/rest-api/deps.edn
  modules/server/build.clj
  modules/terminology-service/deps.edn
Labels: dependencies

#2657 Update Tools Build
  deps.edn
  modules/db/deps.edn
  modules/fhir-structure/deps.edn
  modules/job-async-interaction/deps.edn
  modules/job-compact/deps.edn
  modules/job-re-index/deps.edn
  modules/job-scheduler/deps.edn
  modules/kv/deps.edn
  modules/metrics/deps.edn
  modules/server/deps.edn
  modules/terminology-service/deps.edn
Labels: dependencies

#2667 Update Terminology Service Performance Docs
  docs/performance/terminology-service/data/value-set-validate-code-alpha-id.csv
  docs/performance/terminology-service/data/value-set-validate-code-atc.csv
  docs/performance/terminology-service/data/value-set-validate-code-icd-10-gm.csv
  docs/performance/terminology-service/data/value-set-validate-code-laboratory-observation.csv
  docs/performance/terminology-service/data/value-set-validate-code-snomed-ct-body-site.csv
  docs/performance/terminology-service/data/value-set-validate-code-snomed-ct-diagnoses.csv
  docs/performance/terminology-service/plots/value-set-validate-code-alpha-id.png
  docs/performance/terminology-service/plots/value-set-validate-code-atc.png
  docs/performance/terminology-service/plots/value-set-validate-code-icd-10-gm.png
  docs/performance/terminology-service/plots/value-set-validate-code-laboratory-observation.png
  docs/performance/terminology-service/plots/value-set-validate-code-snomed-ct-body-site.png
  docs/performance/terminology-service/plots/value-set-validate-code-snomed-ct-diagnoses.png
  docs/performance/terminology-service/value-set-validate-code-icd-10-gm.gnuplot
  docs/performance/terminology-service/value-set-validate-code-snomed-ct-body-site.gnuplot
Labels: documentation, performance

#2679 Update Vitepress Deps
  docs/package-lock.json
Labels: dependencies

#2680 Fail pre-push-image on Failing Deps
  .github/workflows/build.yml
Labels: ci

#2678 Sign Docker Images
  .github/workflows/build.yml
  docs/deployment.md
Labels: ci

#2688 Push the Same Image to GHCR and DockerHub
  .github/workflows/build.yml
Labels: ci

#2694 Update Reitit to v0.9.0
  modules/admin-api/deps.edn
  modules/rest-util/deps.edn
Labels: dependencies

#2697 Cache Clojure GitLibs
  .github/workflows/build.yml
Labels: ci

#2698 Improve Docker Image verification Docu
  docs/deployment.md
Labels: ci

#2707 Remove Choice Type Cache from Module fhir-structure
  modules/fhir-structure/deps.edn
  modules/fhir-structure/src/blaze/fhir/spec/impl.clj
Labels: dependencies, cleanup

#2708 Remove Dependencies
  modules/byte-buffer/Makefile
  modules/byte-string/Makefile
  modules/byte-string/deps.edn
  modules/byte-string/src/blaze/byte_string.clj
  modules/cache-collector/deps.edn
  modules/db/test/blaze/db/tx_log/local_test.clj
  modules/fhir-test-util/deps.edn
  modules/luid/deps.edn
  modules/module-base/deps.edn
  modules/page-id-cipher/deps.edn
  modules/test-util/deps.edn
Labels: dependencies, cleanup
