Repository samply/blaze, pull requests merged in 2025-01, with the labels that each got.

#2291 Pass Parameters Expand Terminology Tests
  .github/terminology-tests/parameters-expand.sh
  .github/terminology-tests/remove-r5-tests.jq
  .github/workflows/build.yml
  modules/operation-value-set-expand/src/blaze/fhir/operation/value_set/expand.clj
  modules/operation-value-set-expand/test/blaze/fhir/operation/value_set/expand_test.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/default.clj
  modules/terminology-service/src/blaze/terminology_service/local/value_set/expand.clj
  modules/terminology-service/src/blaze/terminology_service/spec.clj
  modules/terminology-service/test/blaze/terminology_service/local_test.clj
Labels: enhancement

#2295 Update MII Terminology Resources
  .github/value-set-expand/package-lock.json
  .github/value-set-expand/package.json
Labels: dependencies, ci

#2294 Fix Optimised FHIR Search with Subject References
  modules/db/src/blaze/db/node.clj
  modules/db/test/blaze/db/api_test.clj
Labels: bug

#2255 Improve naming (preparation for #2126)
  modules/rest-util/src/blaze/middleware/fhir/output.clj
Labels: module:rest-util, cleanup

#2308 Fix Binary Output in Case of Decoding Errors
  modules/rest-util/src/blaze/middleware/fhir/output.clj
  modules/rest-util/test/blaze/middleware/fhir/output_test.clj
Labels: bug

#2309 Allow more Search Params in Optimization
  modules/db/src/blaze/db/impl/search_param/token.clj
  modules/db/src/blaze/db/node.clj
  modules/db/test/blaze/db/api_test.clj
  modules/db/test/blaze/db/search_param_registry_test.clj
Labels: module:db

#2311 Update metosin/muuntaja to v0.6.11
  modules/rest-util/deps.edn
Labels: dependencies

#2312 Update clj-kondo to v2024.11.14
  .github/workflows/build.yml
Labels: dependencies

#2323 Add Logo and Lexend Font to UI
  modules/frontend/package-lock.json
  modules/frontend/package.json
  modules/frontend/src/app.html
  modules/frontend/src/routes/+layout.svelte
  modules/frontend/static/apple-touch-icon.png
  modules/frontend/static/blaze-logo.svg
  modules/frontend/static/favicon-96x96.png
  modules/frontend/static/favicon.ico
  modules/frontend/static/favicon.png
  modules/frontend/static/favicon.svg
  modules/frontend/tailwind.config.ts
Labels: module:frontend

#2324 Improve Performance Tests of Code Patient Search
  docs/performance/fhir-search.md
  docs/performance/fhir-search/code-date-patient-search.sh
  docs/performance/fhir-search/code-patient-search.sh
  docs/performance/fhir-search/util.sh
Labels: documentation

#2333 Remove Time Sensitive CQL Query
  .github/workflows/build.yml
Labels: test-fix

#2347 Improve Binary Download tests
  modules/rest-util/test/blaze/middleware/fhir/output_test.clj
Labels: cleanup

#2360 Improve Terminology Service Documentation
  docs/api/operation-code-system-validate-code.md
  docs/api/operation-value-set-expand.md
  docs/api/operation-value-set-validate-code.md
  modules/terminology-service/test/blaze/terminology_service/local_test.clj
Labels: documentation

#2363 Improve Documentation
  .github/validation/validate.sh
  .github/value-set-expand/expand-all.sh
  CHANGELOG.md
  LICENSE
  README.md
  docs/.vitepress/config.ts
  docs/api.md
  docs/api/interaction/batch.md
  docs/api/interaction/capabilities.md
  docs/api/interaction/create.md
  docs/api/interaction/delete-history.md
  docs/api/interaction/delete.md
  docs/api/interaction/history-instance.md
  docs/api/interaction/history-system.md
  docs/api/interaction/history-type.md
  docs/api/interaction/read.md
  docs/api/interaction/search-system.md
  docs/api/interaction/search-type.md
  docs/api/interaction/transaction.md
  docs/api/interaction/update.md
  docs/api/interaction/vread.md
  docs/api/operation/code-system-validate-code.md
  docs/api/operation/compact.md
  docs/api/operation/measure-evaluate-measure.md
  docs/api/operation/patient-everything.md
  docs/api/operation/patient-purge.md
  docs/api/operation/value-set-expand.md
  docs/api/operation/value-set-validate-code.md
  docs/blaze-logo.svg
  docs/cql-queries.md
  docs/cql-queries/blazectl.md
  docs/deployment/README.md
  docs/deployment/environment-variables.md
  docs/deployment/manual-deployment.md
  docs/deployment/standalone-backend.md
  docs/implementation/cql.md
  docs/index.md
  docs/package-lock.json
  docs/terminology-service.md
  docs/terminology-service/loinc.md
  docs/terminology-service/snomed-ct.md
  docs/terminology-service/ucum.md
  modules/operation-code-system-validate-code/README.md
  modules/operation-value-set-expand/README.md
  modules/operation-value-set-validate-code/README.md
  modules/rest-api/src/blaze/rest_api/capabilities_handler.clj
  modules/rest-api/test/blaze/rest_api/capabilities_handler_test.clj
  modules/terminology-service/src/blaze/terminology_service/local.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/loinc/context.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/loinc/filter/regex.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/sct.clj
  modules/terminology-service/src/blaze/terminology_service/local/code_system/sct/util.clj
  modules/terminology-service/test/blaze/terminology_service/local/code_system/sct/util_test.clj
  modules/terminology-service/test/blaze/terminology_service/local_test.clj
  resources/blaze.edn
Labels: documentation
