Repository samply/blaze, pull requests merged in 2025-08, with the labels that each got.

#2875 Update blazectl
  .github/scripts/install-blazectl.sh
  .github/workflows/build.yml
  renovate.json
Labels: dependencies

#2880 DB Cleanup
  modules/db/src/blaze/db/api.clj
  modules/db/src/blaze/db/api_spec.clj
  modules/db/src/blaze/db/impl/batch_db/patient_everything.clj
  modules/db/src/blaze/db/impl/index/compartment/resource.clj
  modules/db/src/blaze/db/impl/index/compartment/search_param_value_resource.clj
  modules/db/src/blaze/db/impl/index/resource_as_of.clj
  modules/db/src/blaze/db/impl/index/resource_handle.clj
  modules/db/src/blaze/db/impl/index/resource_search_param_value.clj
  modules/db/src/blaze/db/impl/index/search_param_value_resource.clj
  modules/db/src/blaze/db/impl/search_param.clj
  modules/db/src/blaze/db/impl/search_param/date.clj
  modules/db/src/blaze/db/impl/search_param/quantity.clj
  modules/db/src/blaze/db/impl/search_param/string.clj
  modules/db/src/blaze/db/impl/search_param/token.clj
  modules/db/src/blaze/db/impl/search_param/util.clj
  modules/db/test/blaze/db/api_test.clj
Labels: cleanup

#2917 Update Node Packages
  modules/frontend-e2e/package-lock.json
  modules/frontend/package-lock.json
Labels: dependencies, module:frontend

#2922 Use External Library for Heroicons
  modules/frontend/package-lock.json
  modules/frontend/package.json
  modules/frontend/src/lib/breadcrumb/entry.svelte
  modules/frontend/src/lib/breadcrumb/home.svelte
  modules/frontend/src/lib/jobs/status-round.svelte
  modules/frontend/src/lib/tailwind/dropdown.svelte
  modules/frontend/src/lib/total-card.svelte
  modules/frontend/src/lib/values/util/extern-link-icon.svelte
  modules/frontend/src/lib/values/util/external-link.svelte
  modules/frontend/src/routes/+layout.svelte
  modules/frontend/src/routes/ValueSet/[id=id]/$expand/+page.svelte
  modules/frontend/src/routes/[type=type]/[id=id]/$graph/+page.svelte
  modules/frontend/src/routes/[type=type]/search-forum/button-add.svelte
  modules/frontend/src/routes/[type=type]/search-forum/button-move-down.svelte
  modules/frontend/src/routes/[type=type]/search-forum/button-move-up.svelte
  modules/frontend/src/routes/[type=type]/search-forum/button-remove.svelte
  modules/frontend/src/routes/[type=type]/search-forum/search-param-combo-box.svelte
  modules/frontend/src/routes/[type=type]/search-forum/value-combo-box.svelte
  modules/frontend/src/routes/__admin/dbs/database-card.svelte
  modules/frontend/src/routes/__admin/jobs/new/+page.svelte
  modules/frontend/src/routes/__admin/jobs/new/compact/+page.svelte
  modules/frontend/src/routes/__admin/jobs/new/input-text-error.svelte
  modules/frontend/src/routes/__admin/jobs/task-row.svelte
  modules/frontend/src/routes/metadata/check.svelte
  modules/frontend/src/routes/metadata/download.svelte
  modules/frontend/src/routes/metadata/interaction-td.svelte
  modules/frontend/src/routes/metadata/metadata-card.svelte
  modules/frontend/src/routes/metadata/x-mark.svelte
Labels: refactoring, module:frontend

#2923 Add More FHIR Search Performance Data
  docs/api/interaction/search-type.md
  docs/performance/fhir-search.md
  docs/performance/fhir-search/simple-code-search-download-1M.png
  docs/performance/fhir-search/simple-code-search-download-1M.txt
Labels: documentation

#2934 Update Frontend Dependencies
  modules/frontend-e2e/package-lock.json
  modules/frontend/package-lock.json
  modules/frontend/package.json
Labels: dependencies

#2936 Update HAPI to v8.4.0
  modules/admin-api/deps.edn
Labels: dependencies

#2939 Extract Bundle Link Creation into a Function
  modules/admin-api/test/blaze/admin_api_test.clj
  modules/fhir-test-util/src/blaze/fhir/test_util.clj
  modules/interaction/src/blaze/interaction/history/instance.clj
  modules/interaction/src/blaze/interaction/history/system.clj
  modules/interaction/src/blaze/interaction/history/type.clj
  modules/interaction/src/blaze/interaction/history/util.clj
  modules/interaction/src/blaze/interaction/search_compartment.clj
  modules/interaction/src/blaze/interaction/search_system.clj
  modules/interaction/src/blaze/interaction/search_type.clj
  modules/interaction/test/blaze/interaction/history/instance_test.clj
  modules/interaction/test/blaze/interaction/history/system_test.clj
  modules/interaction/test/blaze/interaction/history/type_test.clj
  modules/interaction/test/blaze/interaction/history/util_spec.clj
  modules/interaction/test/blaze/interaction/history/util_test.clj
  modules/interaction/test/blaze/interaction/search_compartment_test.clj
  modules/interaction/test/blaze/interaction/search_system_test.clj
  modules/interaction/test/blaze/interaction/search_type_test.clj
  modules/interaction/test/blaze/interaction/transaction_test.clj
  modules/operation-patient-everything/src/blaze/operation/patient/everything.clj
  modules/operation-patient-everything/test/blaze/operation/patient/everything_test.clj
  modules/rest-util/src/blaze/interaction/search/util.clj
  modules/rest-util/src/blaze/interaction/search/util/spec.clj
  modules/rest-util/test/blaze/interaction/search/util_test.clj
  modules/spec/src/blaze/spec.clj
  profiling/blaze/profiling.clj
  resources/blaze.edn
  src/blaze/system.clj
  test/blaze/system_test.clj
Labels: refactoring, module:interaction, module:rest-util

#2943 Prevent Playwright Install on Lint
  .github/workflows/build.yml
  modules/frontend-e2e/Makefile
Labels: ci
