Repository samply/blaze, pull requests merged in 2025-04, with the labels that each got.

#2559 Improve Full Standalone Documentation.
  docs/deployment/full-standalone.md
  docs/deployment/full-standalone/screenshots/docker-bypass-proxy.png
Labels: documentation

#2562 Improve Terminology Operation Performance
  modules/operation-code-system-validate-code/src/blaze/fhir/operation/code_system/validate_code.clj
  modules/operation-value-set-expand/src/blaze/fhir/operation/value_set/expand.clj
  modules/operation-value-set-validate-code/src/blaze/fhir/operation/value_set/validate_code.clj
  modules/rest-util/src/blaze/handler/fhir/util.clj
  modules/rest-util/src/blaze/handler/fhir/util_spec.clj
  modules/rest-util/test/blaze/handler/fhir/util_test.clj
Labels: performance

#2569 Update clj-kondo v2025.04.07
  .github/workflows/build.yml
  modules/cql/Makefile
  modules/db-tx-log/Makefile
  modules/fhir-path/Makefile
  modules/job-scheduler/Makefile
  modules/kv/Makefile
  modules/terminology-service/src/blaze/terminology_service/local.clj
Labels: dependencies

#2586 Refactor Integration Tests
  .github/scripts/batch-metadata.sh
  .github/scripts/batch.sh
  .github/scripts/check-date-search.sh
  .github/scripts/conditional-delete-type/check-referential-integrity-violated.sh
  .github/scripts/create-patient-batch.sh
  .github/scripts/util.sh
  .github/workflows/build.yml
Labels: refactoring, cleanup

#2589 Update Vitepress Used for Generating Docs
  docs/package-lock.json
Labels: dependencies

#2590 Update Frontend
  modules/frontend/package-lock.json
Labels: dependencies

#2591 Update Sushi
  job-ig/package-lock.json
  job-ig/package.json
Labels: dependencies

#2595 Remove Adapters Auto and Static from Frontend
  modules/frontend/package-lock.json
  modules/frontend/package.json
Labels: dependencies, cleanup, module:frontend

#2600 Update Frontend E2E Dependencies
  modules/frontend-e2e/Makefile
  modules/frontend-e2e/package-lock.json
  modules/frontend-e2e/package.json
  modules/frontend-e2e/src/code-system.spec.ts
  modules/frontend-e2e/test-data/.npmrc
  modules/frontend-e2e/test-data/Makefile
  modules/frontend-e2e/test-data/package.json
  modules/frontend-e2e/upload.sh
Labels: dependencies

#2611 Update Validator Download URL
  .github/scripts/install-validator.sh
  docs/terminology-service/validation.md
  job-ig/Makefile
  modules/job-async-interaction/Makefile
Labels: documentation, dependencies, cleanup

#2619 Improve documentation.
  docs/architecture.md
  docs/cql-queries/api.md
  docs/deployment/full-standalone.md
  docs/frontend.md
  docs/implementation/database.md
  docs/implementation/fhir-data-model.md
Labels: documentation, cleanup
